### ISSUE TITLE
No data?

### ISSUE THREAD

**Issue by BrockReece** [logstash-plugins/logstash-input-cloudwatch#10]
Hi,

I was wondering if someone could help me?

I have followed your readme and it seems like the requests to cloudwatch are successful but there is no output?

I have included my config below and a verbose log output.

```js
input {
  cloudwatch {
    namespace => "AWS/EC2"
    metrics => [ "CPUUtilization" ]
    filters => { "tag:Monitoring" => "Yes" }

    region => "eu-west-1"
    access_key_id => "MYKEY"
    secret_access_key => "Secret Access"
  }
}

output {
  stdout {}
}
```

```cli
[AWS CloudWatch 200 1.788 0 retries] list_metrics(:namespace=>"AWS/EC2")
 {:level=>:info}
Polling metric CPUUtilization {:level=>:info}
Filters: [{:name=>"tag:Monitoring", :values=>["Yes"]}] {:level=>:info}
[AWS EC2 200 0.389 0 retries] describe_instances(:filters=>[{:name=>"tag:Monitoring",:values=>["Yes"]}])
 {:level=>:info}
```

Cheers
Brock

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
