### ISSUE TITLE
AWS/EC2 giving only 2 datasets, while 3 datasets were expected

### ISSUE THREAD

**Issue by subhash12** [logstash-plugins/logstash-input-cloudwatch#4]
Using the dafault values for Interval (15 minutes) and Period (5 minutes).
AWS/RDS is providing 3 datasets for the above Interval, while AWS/EC2 is only giving 2 datasets.

**Comment by dennis-bsi** [comment]
I'm having the same issue with AWS/EC2 metrics.  Put it on 5min/5min and 75% of my instances never return metrics, even though they're there.  I have verified time is properly set.

**Comment by subhash12** [comment]
@dennis-bsi I too was suspecting the slowness of Cloudwatch to return the metrics. But for RDS, I was receiving all. After moving back the interval vindow to 5 minutes, Im getting all the datasets, Thanks.

**Comment by tomaszrichert** [comment]
I'm experiencing exact same problem, and I will have to modify code as above. Is it possible to release new version with 'delay' parameter ?
