### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by riccardofreixo** [logstash-plugins/logstash-input-cloudwatch#5]
Thanks a lot for this plugin, I'm glad I found it, it does exactly what I needed it to do. :smile: 

However when installing it with the logstash plugin manager, I had version 1.1.0 installed (since it gets the latest version from rubygems.org), which happens to be broken. Just tested the latest version of master in this repo and it works great.

Would really help with automation if a working version was in rubygems.org. Any chance of that happening any time soon?

**Comment by jrgns** [comment]
@riccardofreixo I'm glad it works for you!

I just pushed the gem to rubygems. Please check, and let me know if you have any issues!

**Comment by riccardofreixo** [comment]
Thanks a lot!
