### ISSUE TITLE
Cloudwatch fails when setting interval

### ISSUE THREAD

**Issue by aabed** [logstash-plugins/logstash-input-cloudwatch#6]
Any number but 900 will result in this

## Config

cloudwatch {
         namespace => "AWS/EC2"
         metrics => [ "CPUUtilization" ]
         interval => 400
         filters => { "tag:Monitoring" => "Yes" }
         region => "us-east-1"
       }

## Error

{:timestamp=>"2016-06-18T22:04:57.214000+0000", :message=>"Pipeline aborted due to error", :exception=>#<RuntimeError: Interval must be divisible by peruid>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-cloudwatch-1.1.3/lib/logstash/inputs/cloudwatch.rb:126:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:330:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:329:in `start_inputs'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:180:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}

**Comment by aabed** [comment]
@jrgns

**Comment by jrgns** [comment]
@aabed Hey, for some reason the error message is not being shown. It reads:

`Interval must be divisible by period`

If the interval is not divisible by the period, the metrics will be calculated for overlapping periods. The following will work:

```
  cloudwatch {
    namespace => "AWS/EC2"
    metrics => [ "CPUUtilization" ]
    interval => 400
    period => 200
    filters => { "tag:Monitoring" => "Yes" }
    region => "us-east-1"
  }

```

**Comment by aabed** [comment]
I see , thanks
